import argparse
from src.train import model_train
from src.utils import init_dist, seed_everything
import os


def main():
    parser = argparse.ArgumentParser(description="Train deep learning model")
    parser.add_argument('--h5_path', required=True,
                        help='The path of the h5 file generated by generate.sh. Note: this parameter should be the same with it in data procession.')
    parser.add_argument('--model_save_path', type=str, default='ANNEVO.pt', help='Path to save the trained model.')
    parser.add_argument('--learning_rate', type=float, default=0.0001, help='Learning rate.')
    parser.add_argument('--epoch', type=int, default=100, help='The number of max epochs.')
    parser.add_argument('--batch_size', type=int, default=32, help='The number of samples in a batch.')
    parser.add_argument('--patience', type=int, default=5, help='The patience of early stop mechanism.')
    parser.add_argument('--warmup_steps', type=int, default=10000, help='The number of warmup steps.')

    parser.add_argument('--window_size', type=int, default=30720,
                        help='The number of bases in a window. Note: this parameter should be the same with it in data procession and gene decoding.')
    parser.add_argument('--flank_length', type=int, default=5120,
                        help='The length of flanking sequence. Note: this parameter should be the same with it in data procession and gene decoding.')
    parser.add_argument('--channels', type=int, default=64, help='The number of channels in Conv layer. Note: this parameter should be the same with it in gene decoding.')
    parser.add_argument('--dim_feedforward', type=int, default=768,
                        help='The dimension of linear layer in Transformer encoder. Note: this parameter should be the same with it in gene decoding.')
    parser.add_argument('--num_encoder_layers', type=int, default=6,
                        help='The number of transformer encoder layer in each block. Note: this parameter should be the same with it in gene decoding.')
    parser.add_argument('--num_heads', type=int, default=8,
                        help='The number of attention heads in multi-heads attention. Note: this parameter should be the same with it in gene decoding.')
    parser.add_argument('--num_blocks', type=int, default=5, help='The number of Conv blocks. Note: this parameter should be the same with it in gene decoding.')
    parser.add_argument('--num_branches', type=int, default=8,
                        help='The number of simulated evolutionary branches. Note: this parameter should be the same with it in gene decoding.')
    args = parser.parse_args()

    output_dir = os.path.dirname(args.model_save_path)
    if output_dir and not os.path.exists(output_dir):
        os.makedirs(output_dir)

    model_train(args.model_save_path, args.h5_path, args.learning_rate, args.epoch, args.batch_size, args.patience, args.warmup_steps,
                args.window_size, args.flank_length, args.channels, args.dim_feedforward, args.num_encoder_layers,
                args.num_heads, args.num_blocks, args.num_branches)


if __name__ == '__main__':
    init_dist()
    seed_everything(2024)
    main()
