import os

import argparse

from model_training.src.seq_step import model_train
from model_training.src.utils import cleanup_dist, get_rank, init_dist, is_main_process, seed_everything


def main():
    parser = argparse.ArgumentParser(description="Train deep learning model")
    parser.add_argument('--train_h5_path', required=True,
                        help='The path of the training file generated by generate.sh.')
    parser.add_argument('--val_h5_path', required=True,
                        help='The path of the val file generated by generate.sh.')
    parser.add_argument('--train_h5_path_2', required=True,
                        help='The path of the training file generated by generate.sh.')
    parser.add_argument('--val_h5_path_2', required=True,
                        help='The path of the val file generated by generate.sh.')
    parser.add_argument(
        "--length_config",
        required=True,
        choices=("longer", "normal"),
        help="Sequence-length preset: longer=102400 bp, normal=30720 bp.",
    )
    parser.add_argument('--model_save_path', type=str, default='ANNEVO.pt', help='Path to save the trained model.')
    args = parser.parse_args()

    LEARNING_RATE = 0.0001
    EPOCH = 100
    BATCH_SIZE = 8
    PATIENCE = 5
    WARMUP_STEPS = 16000
    length_config = {
        'longer': [102400, 12800, 32],
        'normal': [30720, 5120, 32],
    }
    WINDOW_SIZE, FLANK_LENGTH, LOCAL_PATTERN_SIZE = length_config[args.length_config]
    output_dir = os.path.dirname(args.model_save_path)
    if is_main_process() and output_dir and not os.path.exists(output_dir):
        os.makedirs(output_dir)

    model_train(args.model_save_path, args.train_h5_path, args.val_h5_path, args.train_h5_path_2, args.val_h5_path_2,
                LEARNING_RATE, EPOCH, BATCH_SIZE, PATIENCE, WARMUP_STEPS, WINDOW_SIZE, FLANK_LENGTH, LOCAL_PATTERN_SIZE)


if __name__ == '__main__':
    init_dist()
    try:
        seed_everything(42 + get_rank())
        main()
    finally:
        cleanup_dist()
